#!/bin/sh

# default options
version=latest
httpsport=44342

# handle arguments
while test $# -gt 0; do
	case "$1" in

		-p|--port)
			shift
			if [ $# -gt 0 ]; then
				httpsport=$1
			fi
			shift
			;;

	  -v|--version)
	    shift
	    if [ $# -gt 0 ]; then
	      if [ ! -z "$1" ]; then
	        version=$1
	      fi
	    fi
	    shift
	    ;;

		*)
			break
			;;
	esac
done

name="osprey-service"

s6="-e S6_READ_ONLY_ROOT=1 --read-only --tmpfs /var:rw,exec"

binds="--mount type=bind,src=/tmp,dst=/tmp"
binds="$binds --volume osprey-service:/home/osprey"

ports="-p $httpsport:$httpsport/tcp -e HTTPS_PORT=$httpsport"

# nope nope nope, giving up on OSX for now
# ask docker-machine for docker connection info, if it exists
#if command -v docker-machine; then
#  # TODO: this is specific to the dlab environment... how to make general?
#  #       docker DOES NOT make it easy to install docker as a daemon on OSX
#  export VBOX_USER_HOME=/Users/docker/vbox
#  eval `docker-machine -s /Users/docker/machine env`
#fi

docker run --name $name --rm $s6 $binds $ports osprey/service:$version
