# This build script is used to compile a runnable jar on sourcehut
image: fedora/latest
environment:
    LC_ALL: en_US.utf8
    JAVA_HOME: ~/software/jdk
packages: []
sources:
  - https://git.sr.ht/~nsg/osprey
tasks:
  - download-java: |
      mkdir ~/software
      cd ~/software
      wget https://download.java.net/java/GA/jdk19.0.2/fdb695a9d9064ad6b064dc6df578380c/7/GPL/openjdk-19.0.2_linux-x64_bin.tar.gz
      tar xf openjdk-19.0.2_linux-x64_bin.tar.gz
      mv jdk-19.0.2 jdk
  - gradlew-assemble: |
      cd osprey
      ./gradlew assembleDist
      ln build/distributions/osprey*.tar build/distributions/osprey-srht.tar
artifacts:
    - osprey/build/distributions/osprey-srht.tar
