# This build script is used to compile a runnable jar on sourcehut
image: fedora/latest
environment:
    LC_ALL: en_US.utf8
    JAVA_HOME: ~/software/jdk
packages:
  - wget
sources:
  - https://git.sr.ht/~nsg/osprey
tasks:
  - download-java: |
      URL=https://github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%2B7/OpenJDK19U-jdk_x64_linux_hotspot_19.0.2_7.tar.gz
      mkdir ~/software
      cd ~/software
      wget $URL
      tar xf OpenJDK19U-jdk_x64_linux_hotspot_19.0.2_7.tar.gz
      mv jdk-19.0.2+7 jdk
  - gradlew-assemble: |
      cd osprey
      ./gradlew assembleDist
      ln build/distributions/osprey*.tar build/distributions/osprey-srht.tar
artifacts:
    - osprey/build/distributions/osprey-srht.tar
