package edu.duke.cs.osprey.partitionfunctionbounds.continuous;

/**
 * Represents a feature map generated by fixing one element in the kernel. 
 * @author aditya
 */
public class FeatureMap {
	
	// kernel that this feature map is constructed from
	Kernel k;
	
	// value in domain from which feature map was generated
	double[] loc; 

	/** 
	 * A feature map is determined by a kernel function and a variable in the
	 * domain
	 * @param k
	 * @param x
	 */
	public FeatureMap(Kernel k, double[] x) {
		this.k = k;
		this.loc = x;
	}
	
        /**
         * Returns the value of the feature map at a particular point
         * @param y
         * @return value
         */
	public double eval(double[] y) {
		return k.eval(this.loc, y);
	}
	
        /**
         * Returns the "location" of the feature map 
         * @return 
         */
	public double[] getLoc() {
		return this.loc;
	}
        
	/**
         * Returns the kernel used to generate the feature map 
         * @return 
         */
	public Kernel getKernel() {
		return this.k;
	}
}
