/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.duke.cs.osprey.structure;

import java.io.Serializable;
import java.util.ArrayList;

/**
 *
 * @author mhall44
 */
public class Molecule implements Serializable {
    
    public ArrayList<Residue> residues = new ArrayList<>();
    
    //also might have secondary structure elements...

    //Molecule will usually be generated by PDBFileReader.readPDBFile
    public Molecule(){
        
    }
    
    
    
    public Residue getResByPDBResNumber(String resNumber){
        
        for(Residue res : residues){
            if(res.getPDBResNumber().equalsIgnoreCase(resNumber))
                return res;
        }
        
        throw new RuntimeException("ERROR: Can't find residue in molecule with PDB-based number "+resNumber);
    }
    
    
    public void appendResidue(Residue res){
        //Add a residue to the end of the molecule
        res.indexInMolecule = residues.size();
        residues.add(res);
    }
    
    public void deleteResidue(int resIndex){
        //delete the residue with the specified index in residues
        residues.remove(resIndex);
        //this changes the indexInMolecule for all subsequent residues
        for(int index2=resIndex; index2<residues.size(); index2++)
            residues.get(index2).indexInMolecule--;
    }
    
    
}
